
# {{{ health checkers
### profiles - users - auth
GET http://localhost:8001/health

GET http://localhost:8002/health

GET http://localhost:8003/health

### fmc
GET http://localhost:8005/health

### questions - answers
GET http://localhost:8011/health

GET http://localhost:8012/health

### modules
GET http://localhost:8021/health

### resources - papers
GET http://localhost:8031/health

GET http://localhost:8032/health

### local
GET http://localhost:8000/health
# }}}

### auth bypass
GET http://localhost:8003/auth/bypass/1
Accept: application/json

# {{{ papers

GET http://localhost:8000/api/v1/paper/
Accept: application/json
Authorization: Bearer 

GET http://localhost:8000/api/v1/paper/2
Accept: application/json
Authorization: Bearer 

GET http://localhost:8000/api/v1/paper/user/1
Accept: application/json
Authorization: Bearer 

GET http://localhost:8000/api/v1/paper/last
Accept: application/json
Authorization: Bearer 

POST http://localhost:8000/api/v1/paper
Accept: application/json
Authorization: Bearer 
Content-type: application/json

{
  "user_id": 2,
  "resource_id": 1,
  "project_id": 1
}

POST http://localhost:8041/api/v1/logic/checker
Accept: application/json
Authorization: Bearer 
Content-type: application/json

{
  "id": 1,
  "user_id": 2,
  "user_record": { "step": 5, "mood": 45 },
  "project_id": 1,
  "resource_id": 50,
  "completed": true,
  "answers": [
    { "question_id": 1, "answer": "10" },
    { "question_id": 2, "answer": "10" },
    { "question_id": 3, "answer": "10" },
    { "question_id": 5, "answer": "5" }
  ]
}

POST http://localhost:8000/api/v1/paper/1
Accept: application/json
Authorization: Bearer 
Content-type: application/json

#"user_record": "{'step': 1, 'mood': '40'}",
{
  "id": 1,
  "user_id": 1,
  "user_record": { "step": 1, "mood": 45 },
  "project_id": 1,
  "resource_id": 10,
  "completed": false,
  "answers": [
    { "question_id": 1, "answer": "10" },
    { "question_id": 2, "answer": "10" },
    { "question_id": 3, "answer": "10" },
    { "question_id": 5, "answer": "5" }
  ]
}

PUT http://localhost:8000/api/v1/paper/1
Accept: application/json
Authorization: Bearer 
Content-type: application/json

{
  "user_id": 1,
  "resource_id": 50,
  "project_id": 1,
  "completed": true
}

# }}}
