
# {{{ health checkers
### profiles - users - auth
GET http://localhost:8001/health

GET http://localhost:8002/health

GET http://localhost:8003/health

### fmc
GET http://localhost:8005/health

### questions - answers
GET http://localhost:8011/health

GET http://localhost:8012/health

### modules
GET http://localhost:8021/health

### resources - papers
GET http://localhost:8031/health

GET http://localhost:8032/health

### local
GET http://localhost:8000/health
# }}}

### auth bypass
GET http://localhost:8003/auth/bypass/1
Accept: application/json

# {{{ papers

GET http://localhost:8000/api/v1/paper/
Accept: application/json
Authorization: Bearer 

GET http://localhost:8000/api/v1/paper/1
Accept: application/json
Authorization: Bearer 

GET http://localhost:8000/api/v1/paper/user/1
Accept: application/json
Authorization: Bearer 

GET http://localhost:8000/api/v1/paper/project/1/lasts
Accept: application/json
Authorization: Bearer 

POST http://localhost:8000/api/v1/paper
Accept: application/json
Authorization: Bearer 
Content-type: application/json

{
  "user_id": 2,
  "resource_id": 2,
  "project_id": 1
}

POST http://localhost:8000/api/v1/logic/checker/push/project/1

POST http://localhost:8041/api/v1/logic/checker/push/
Accept: application/json
Authorization: Bearer 
Content-type: application/json

{
  "id": 1,
  "user_id": 1,
  "user_record": { "step": 5, "mood": 45 },
  "project_id": 1,
  "resource_id": 50,
  "completed": true,
  "answers": [
    { "question_id": 1, "answer": "10" },
    { "question_id": 2, "answer": "10" },
    { "question_id": 3, "answer": "10" },
    { "question_id": 5, "answer": "5" }
  ]
}

POST http://localhost:8000/api/v1/paper/1
Accept: application/json
Authorization: Bearer 
Content-type: application/json

{
  "id": 1,
  "user_id": 1,
  "user_record": { "step": 3, "mood": 45 },
  "project_id": 1,
  "resource_id": 30,
  "completed": false,
  "answers": [
    { "question_id": 1, "answer": "10" },
    { "question_id": 2, "answer": "10" },
    { "question_id": 3, "answer": "10" },
    { "question_id": 4, "answer": "10" },
    { "question_id": 6, "answer": "10" },
    { "question_id": 5, "answer": "5" }
  ]
}

PUT http://localhost:8000/api/v1/paper/1
Accept: application/json
Authorization: Bearer 
Content-type: application/json

{
  "user_id": 1,
  "resource_id": 10,
  "project_id": 1,
  "completed": false
}

PUT http://localhost:8000/api/v1/paper/
Accept: application/json
Authorization: Bearer 
Content-type: application/json

{
  "user_id": 1,
  "resource_id": 20,
  "project_id": 1,
  "completed": true
}

PATCH http://localhost:8000/api/v1/paper/1/completed
Accept: application/json
Authorization: Bearer 
Content-type: application/json

# }}}

# {{{

# create resource til 20
POST http://localhost:8031/api/v1/resource
Accept: application/json
Authorization: Bearer 
Content-Type: application/json

{
  "resource_type": "slides",
  "title": "Título dummy",
  "description": "",
  "content": {
    "slides": [ 1, 2, 3 ]
  }
}

PUT http://localhost:8031/api/v1/resource/10
Accept: application/json
Authorization: Bearer 
Content-Type: application/json

{
  "resource_type": "slides",
  "title": "Título 10",
  "description": "Bla bla",
  "content": {
    "slides": [ 2,3 ]
  }
}

GET http://localhost:8031/api/v1/resource/10
Accept: application/json
Authorization: Bearer 
Content-Type: application/json

# }}}
